# Generated by Django 3.2.7 on 2021-10-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
